### ISSUE TITLE
Publish to NPM

### ISSUE THREAD

**Issue by marshallswain** [feathersjs/canjs-feathers#21]

**Comment by Macrofig** [comment]
Do want. :)

**Comment by marshallswain** [comment]
I'm testing the new version of this today (feathers-client branch).  I imagine that it will be the version we want to publish.

**Comment by daffl** [comment]
I should probably update the readme but basically you now pass it a feathers-client instance and get a Model returned:

```js
var app = feathers().configure(feathers.socketio());
var Model = canFeathers(app);

Model.extend({
  resource: 'todos'
}, {});
```

**Comment by Macrofig** [comment]
Awesome. I'm playing around with Feathers this weekend. Super glad your guys built this. :)

@marshallswain Maybe I'm doing it wrong, but I'm having trouble importing the file using Steal. In your new branch, are you loading it in using a module loader?

**Comment by daffl** [comment]
This should be fixed. The module is available at https://www.npmjs.com/package/canjs-feathers
